In [1]:
import numpy as np

In [4]:
# mathematical operations
x =np.array([[1,2],[3,4]])
y=np.array([[4,5],[6,7]])
# element vise addition
print(x+y)
print(np.add(x,y))
print(np.subtract(x,y)) # multiply , divide ,sqrt are respective functions 

[[ 5  7]
 [ 9 11]]
[[ 5  7]
 [ 9 11]]
[[-3 -3]
 [-3 -3]]


In [5]:
#matrix multiplication / dot product 
print(np.dot(x,y))

[[16 19]
 [36 43]]


In [6]:
# multiplication(dot product) of vectors - Scalar
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a.dot(b))

30


In [7]:
# can be used to sum in a linear matrix
print(a)
print(sum(a))

[1 2 3 4]
10


In [9]:
# np sum function takes another parameter called axis 
#axis =0 . add through coloums
print(x)
print("sum about axis = 0 is" )
print(np.sum(x,axis=0))

[[1 2]
 [3 4]]
sum about axis = 0 is
[4 6]


In [10]:
# stack function 
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [11]:
b = b**2

In [16]:
# to stack function along axis =1 
a=np.stack((a,b) , axis =1)
print(a)

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [20]:
# reshape a numpy array
a=a.reshape((4,2))
print(a)

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [ ]:
# if you dont know the row or column , then write -1
a=a.reshape(())