In [1]:
import numpy as np

In [4]:
# mathematical operations
x =np.array([[1,2],[3,4]])
y=np.array([[4,5],[6,7]])
# element vise addition
print(x+y)
print(np.add(x,y))
print(np.subtract(x,y)) # multiply , divide ,sqrt are respective functions 

[[ 5  7]
 [ 9 11]]
[[ 5  7]
 [ 9 11]]
[[-3 -3]
 [-3 -3]]


In [5]:
#matrix multiplication / dot product 
print(np.dot(x,y))

[[16 19]
 [36 43]]


In [ ]:
# multiplication 