In [3]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape) # it returns tuple of the  dimension

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
b= np.array([[1],[2]])
print(b)

[[1]
 [2]]


In [4]:
print(b.shape)

(2, 1)


In [12]:
# creating array of zeros
zero = np.zeros((3,3))
print(zero)
one = np.ones((1,1))
print(np.ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<function ones at 0x7f5ff8147ae8>


In [14]:
# fill the array with determined constant
c = np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [15]:
#Identity matrix - size square matrix
d=np.eye(4)
print(d)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
#Random martrix
random = np.random.random((2,3))
print(random)

[[0.37168633 0.94771923 0.57875501]
 [0.7624558  0.68425698 0.3263937 ]]


In [18]:
print(random[:,1])
random[1][1:] = 1
print(random[1,1:])

[0.94771923 0.68425698]
[1. 1.]


In [19]:
zero[1,:]=5 # slicing
zero[:,-1]=3 # last row can be selected as coloumn
print(zero)

[[0. 0. 3.]
 [5. 5. 3.]
 [0. 0. 3.]]


In [4]:
intzero = np.zeros((3,3) , dtype= np.int64)

In [5]:
print(intzero.dtype)

int64
